### ISSUE TITLE
multiple years

### ISSUE THREAD

**Issue by peter1125** [AgentEnder/OpenPayrollCrawler#1]
Hi,

thank you for this great code. 

I just had two small things.

1. Openpayroll site seems to have changed since the code was last updated and is parsing the wrong column for the salary information.

2. Some names have multiple years of salary information for one person. Would it be possible to make changes so that it parses all the years?

**Comment by AgentEnder** [comment]
Hey! This crawler was written pretty quickly, but all CSS paths should be easy enough to change. Getting it to support multiple years would be a bit harder.

I'd be open to PR's for either of the two, if you want to prepare one.
